[pytest]
minversion = 6.0
addopts = -ra -q --cov=py_simulation/src --cov-report=html --cov-report=term
testpaths =
    py_simulation/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
